

services:
  landing:
    container_name: landing
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5555:5555"
    environment:
      PORT: 5555
    network_mode: "host"
    networks:
      - master


networks:
  master:
    driver: bridge